name: Build Custom Font

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Font
        run: npm run build -- contents::IosevkaNew

      - name: Upload Font Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Custom-Iosevka-TTF
          path: dist/
